name: Validate

on:
  workflow_call:
    inputs:
      bun_version:
        description: "The version of Bun to use"
        required: false
        default: "1.2.10"
        type: string
      package_dir:
        description: "Directory of the package to validate"
        required: false
        default: "./"
        type: string
      upload_coverage:
        description: "Whether to upload code coverage reports to Codecov"
        required: false
        default: false
        type: boolean
    secrets:
      ORG_CODECOV_TOKEN:
        description: "Token for uploading code coverage reports to Codecov"
        required: false

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.bun_version }}

      - name: Install Dependencies
        run: |
          cd ${{ inputs.package_dir }}
          bun install --frozen-lockfile

      - name: Lint
        run: |
          cd ${{ inputs.package_dir }}
          bun run lint

  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.bun_version }}

      - name: Install Dependencies
        run: |
          cd ${{ inputs.package_dir }}
          bun install --frozen-lockfile

      - name: Test
        run: |
          cd ${{ inputs.package_dir }}
          bun run test

      - name: Upload Coverage
        if: inputs.upload_coverage == true
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.ORG_CODECOV_TOKEN }}
          slug: ${{ github.repository }}
